// <auto-generated />
using System;
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Db.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190728093320_Tariffs")]
    partial class Tariffs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Client.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Balance");

                    b.Property<string>("Comment");

                    b.Property<int>("FullAddressId");

                    b.Property<int>("HouseId");

                    b.Property<string>("HwIpAddress");

                    b.Property<string>("HwPort");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Patronymic");

                    b.Property<string>("Status");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("FullAddressId");

                    b.HasIndex("HouseId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.House.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalNumber");

                    b.Property<string>("Address");

                    b.Property<string>("Comment");

                    b.Property<string>("Number");

                    b.Property<string>("Porch");

                    b.Property<int?>("SubnetId");

                    b.HasKey("Id");

                    b.HasIndex("SubnetId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("Domain.Network.FullAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Grey");

                    b.Property<int?>("SubnetId");

                    b.Property<int?>("WhiteId");

                    b.HasKey("Id");

                    b.HasIndex("SubnetId");

                    b.HasIndex("WhiteId");

                    b.ToTable("FullAddress");
                });

            modelBuilder.Entity("Domain.Network.Subnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Gateway");

                    b.Property<int>("Mask");

                    b.HasKey("Id");

                    b.ToTable("Subnets");
                });

            modelBuilder.Entity("Domain.Network.WhiteAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.HasKey("Id");

                    b.ToTable("WhiteAddress");
                });

            modelBuilder.Entity("Domain.Tariff.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<int>("InputRate");

                    b.Property<bool>("IsPeriodic");

                    b.Property<string>("Name");

                    b.Property<int>("OutputRate");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("Domain.User.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("Domain.Client.Client", b =>
                {
                    b.HasOne("Domain.Network.FullAddress", "FullAddress")
                        .WithMany()
                        .HasForeignKey("FullAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.House.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.House.House", b =>
                {
                    b.HasOne("Domain.Network.Subnet", "Subnet")
                        .WithMany("Houses")
                        .HasForeignKey("SubnetId");
                });

            modelBuilder.Entity("Domain.Network.FullAddress", b =>
                {
                    b.HasOne("Domain.Network.Subnet", "Subnet")
                        .WithMany()
                        .HasForeignKey("SubnetId");

                    b.HasOne("Domain.Network.WhiteAddress", "White")
                        .WithMany()
                        .HasForeignKey("WhiteId");
                });
#pragma warning restore 612, 618
        }
    }
}
